### ISSUE TITLE
Unregister from bower so that I can take the package-name

### ISSUE THREAD

**Issue by hendrikniemann** [ethul/purescript-graphql#1]
Hi @ethul ,

I have been [working on a PureScript wrapper](https://github.com/hendrikniemann/purescript-graphql) for GraphQL.js over the last month. I am ready to publish but currently you have registered the `purescript-graphql` package on bower. Can you unregister it so that I can take over the package name?

**Comment by ethul** [comment]
You should be good to go with the package name.

**Comment by hendrikniemann** [comment]
Thank you!
